[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
crypto_mapp = "2fN9ZMRnTB3MHi3oT3HFJcReY7jTJDDhoQNFKrbTKTTe"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/twentone37/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
