[toolchain]
channel = "stable"

[features]
seeds = false
skip-lint = false

[programs.localnet]
cryptom_protocol = "6gVqqXEwoTX7AZTBYQDEaXntMiBPnTAyBbuMCeqk5avi"

[programs.devnet]
cryptom_protocol = "6gVqqXEwoTX7AZTBYQDEaXntMiBPnTAyBbuMCeqk5avi"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api.devnet.solana.com"
wallet = "/Users/twentone37/my-solana-wallet.json"

#[provider]
#cluster = "localnet"                   
#wallet = "~/.config/solana/id.json"    

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

