name: Deploy Solana Contracts

on:
  push:
    branches:
      - main
      - dev

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    container: projectserum/build:v0.27.0

    steps:
      - uses: actions/checkout@v3

      - name: List rustup toolchains
        run: rustup toolchain list

      - name: Set default toolchain
        run: rustup default stable

      - name: List rustup toolchains
        run: rustup toolchain list

      # - name: Generate new keygen
      #   run: solana-keygen new

      # - name: Set solana target cluster to local
      #   run: solana config set --url http:localhost:8899

      - name: Check solana config
        run: solana config get

      - name: Install yarn dependencies
        run: yarn install

      - name: Build
        run: anchor build

      - name: Run tests
        run: anchor test

      - name: Deploy contracts
        run: |
          source $HOME/.cargo/env
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            solana config set --url mainnet
          else
            solana config set --url devnet
          fi
          anchor deploy
